In [1]:
import pandas as pd
import numpy as np

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
len(npr)

11992

In [5]:
type(npr)

pandas.core.frame.DataFrame

In [8]:
# npr['Article'][0]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv = CountVectorizer(max_df=.9,min_df=2,stop_words='english')

In [17]:
dtm = cv.fit_transform(npr['Article'])

In [18]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [19]:
dtm.shape

(11992, 54777)

In [21]:
type(dtm)

scipy.sparse.csr.csr_matrix

In [22]:
from sklearn.decomposition import LatentDirichletAllocation

In [23]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [24]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='batch', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_components=7, n_jobs=None, n_topics=None, perp_tol=0.1,
             random_state=42, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [26]:
len(cv.get_feature_names())

54777

In [27]:
import random

In [28]:
for i in range(10):
    random_word_id = random.randint(0,54777)
    print(cv.get_feature_names()[random_word_id])
    

gerhard
fibers
recollections
politely
galley
etihad
methodology
anesthesiology
lilac
frosted


In [29]:
for i in range(10):
    random_word_id = random.randint(0,54777)
    print(cv.get_feature_names()[random_word_id])

golden
cornmeal
mckenzie
haha
hipster
lineup
wheelhouse
definitions
grecia
johnson


In [30]:
len(LDA.components_)

7

In [35]:
single_topic = LDA.components_[0]

In [36]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [40]:
single_topic[2475]

0.1428571430851871

In [43]:
single_topic[42993]

6247.245510521096

In [49]:
top_15 = single_topic.argsort()[-15:]

In [50]:
for i in top_15:    
    print(cv.get_feature_names()[i])

companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [52]:
# LDA.components_

In [59]:
for index,topic in enumerate(LDA.components_):
    print(f'Top 15 words in the topic number: {index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

Top 15 words in the topic number: 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


Top 15 words in the topic number: 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


Top 15 words in the topic number: 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


Top 15 words in the topic number: 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


Top 15 words in the topic number: 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


Top 15 words in the topic number: 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music'

In [60]:
topic_result = LDA.transform(dtm)

In [65]:
topic_result[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [66]:
topic_result[0].argmax()

1

In [67]:
#Combining with original data:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [68]:
topic_result.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0], dtype=int64)

In [69]:
npr['Topic']=topic_result.argmax(axis=1)

In [70]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2

In [76]:
dict = {0:'coountry',1:'Defence',2:'family',3:'health',4:'education',5:'Environment',6:'policy'}
npr['Topic_names'] = npr['Topic'].map(dict)

In [77]:
npr.head()

Article  Topic Topic_names
0  In the Washington of 2016, even when the polic...      1     Defence
1    Donald Trump has used Twitter  —   his prefe...      1     Defence
2    Donald Trump is unabashedly praising Russian...      1     Defence
3  Updated at 2:50 p. m. ET, Russian President Vl...      1     Defence
4  From photography, illustration and video, to d...      2      family